# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            tap349
#tagline:          'A Jekyll theme'
#description:      "tap349's blog"
url:              tap349.github.io
baseurl:          /

author:
  name:           tap
  #url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

#github:
  #repo:           https://github.com/poole/hyde
