#==============================================================================
# Setup
#==============================================================================

title:                tap349
tagline:              my blog
description:          my blog
url:                  http://tap349.github.io
baseurl:              /

paginate:             5
excerpt_separator:    <!-- more -->

#==============================================================================
# About/contact
#==============================================================================

author:
  name:               tap
  url:                https://github.com/tap349

#==============================================================================
# Syntax highlighting
#==============================================================================

markdown:             kramdown
#highlighter:          rouge
highlighter:          pygments

# http://kramdown.gettalong.org/options.html
kramdown:
  autolink:           true
  hard_wrap:          false
  input:              GFM

#------------------------------------------------------------------------------
# redcarpet
# NOTE: redcarpet and pygments are no longer supported by github pages!
#------------------------------------------------------------------------------

#markdown:             redcarpet
#highlighter:          pygments

# hard_wrap is no longer available as extension
# https://github.com/vmg/redcarpet
#redcarpet:
  #extensions:
    #- autolink
    #- fenced_code_blocks
    #- highlight
    #- no_intra_emphasis
    #- strikethrough
    #- superscript
    #- tables
    #- underline
    #- with_toc_data

#==============================================================================
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#==============================================================================

permalink:            pretty
#relative_permalinks: true

#==============================================================================
# Assets
#
# We specify the directory for Jekyll so we can use @imports.
#==============================================================================

sass:
  sass_dir:           _sass
  style:              :compressed

#==============================================================================
# Plugins
#==============================================================================

plugins:              [jekyll-paginate, jekyll-gist]

theme:                jekyll-theme-cayman
