# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               tap349
#tagline:             The Jekyll Butler
url:                 http://tap349.github.io
paginate:            5
baseurl:             ''

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              tap349

# Custom vars
pages_list:           { 'About': '/about', 'Archive': '/archive' }
